---
version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: America/Los_Angeles
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
