name = "kitchen"
license = "Apache-2"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = "The theme used for KitchenCI"
homepage = "https://github.com/chef/chef-hugo-theme"
tags = []
features = []
min_version = "0.38"
